spring:
  datasource:
    url: jdbc:mysql://117.17.142.207:3306/real_estate_data?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    password: cs616
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:log4jdbc:mysql://117.17.142.207:3306/realestate_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: cs616
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  main:
    web-application-type: none
  batch:
    job:
      enabled: false
logging:
  level:
    org:
      hibernate: debug
filePath: /var/lib/jenkins/data
serviceKey: \%2BOYuTJYMUl8Rx17U1zJFP35LgxFd5b81a94LTqltyHekTu4WdmXxhaBJePS7Y1\%2FppFV3k6aqdSl4DDG\%2FfylR4w\%3D\%3D
googleKey: AIzaSyCxULkNzEk4-VQDsQFPE1SGvojF104rFFs

